### ISSUE TITLE
Required `json` property not found

### ISSUE THREAD

**Issue by isacaraujo** [advanced-rest-client/api-console-dev-preview#1]
I'm not sure if this repository is under maintenance, but: 

-------
This **BUG** was fetched from this other: [mulesoft-labs/api-console-cli #18](https://github.com/mulesoft-labs/api-console-cli/issues/18).

This package was broken after an update of raml2html/raml2obj.

We need to fix this package before fix the `api-console-cli`.

**Comment by ginus** [comment]
https://github.com/advanced-rest-client/api-console-dev-preview/pull/2
I commit a PR
